name: PHP Mess Detector

on: push

jobs:
  phpmd:
    name: PHP Mess Detector
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP environment
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          tools: phpmd

      - id: phpmd
        name: Run PHP Mess Detector on modified files
        uses: Ana06/get-changed-files@v2.2.0
        with:
          filter: '*.php'
        shell: bash
        run: |
          RETVAL=0
          if [ -s "${{ steps.phpmd.outputs.all }}" ]; then
            FILES=`echo ${{ steps.phpmd.outputs.all }} | paste -sd "," -`
            echo "Running PHPMD on" $FILES
            phpmd $FILES github .github/phpmd-ruleset.xml --exclude 'vendor/*'
            RETVAL=$?
          else
            echo "There are no changes in PHP files (no PHP-MD test performed)"
          fi
          exit $RETVAL
