name: PHP Mess Detector

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ develop ]

jobs:
  ci:
    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: PHP Mess Detector
        uses: php-actions/phpmd@v1.0.0
        with:
          php_version: ${{ matrix.php-version }}
          path: /
          output: text
          ruleset: test/phpmd/ruleset.xml
          suffixes: php
